---
title: "grade_analysis_lab"
author: "Marie JULLIEN"
format: html
editor: visual
---

https://github.com/mariejullien/r-101-grade-analysis.git

```{r}
#| message: false
library(here)
here::i_am("Lab3.qmd")
library(ggplot2)
library(dplyr)
library(tidyr)
library(vroom)
```

## Question 1

```{r}
#| message: false
grades <-vroom(here("grades.csv"))
```

## Question 2

```{r}
grades |> 
  summarise(min_Exam= min(Exam, na.rm=TRUE), max_Exam= max(Exam, na.rm=TRUE), mean_Exam=mean(Exam, na.rm=TRUE), median_Exam=median(Exam, na.rm=TRUE)) |>
knitr::kable()
```

## Question 3

```{r}
num_student_without_fe <- grades |> 
  filter(is.na(Exam)) |>
  nrow()
```

The number of students who did not take the final exam is `r num_student_without_fe`.

## Question 4

```{r}
grades |> filter(Exam != "NA") |> ggplot(aes(x=Exam, na.rm=TRUE)) + geom_histogram(bins=30) + geom_rug() + labs(title='Distribution of grades at the final exam')
```

## Question 5

```{r}
grades |> group_by(Group) |> 
  summarise(n=n()) |>
  knitr::kable()
```

## Question 6

```{r}
grades |> group_by(Group) |> 
  ggplot(aes(y=Group)) + geom_bar() +labs(title="Number of students in each group")
```

## Question 7

### Graphique 1

```{r}
grades |> 
  ggplot(aes(x=Group, y=Exam, na.rm=TRUE)) + geom_boxplot() + labs(title = "Distribution of grades conditionned by the group")
```

### Graphique 2

```{r}
grades |> 
  ggplot(aes(x=Group, y=Exam, na.rm=TRUE)) + geom_violin() +coord_flip() +labs(title="Distribution of grades conditionned by the group")
```

## Question 8 
```{r}
grades |>
  group_by(Group) |>
  summarise(nb_missed_exam = sum(is.na(Exam)))
```
## Question 9 

```{r}
grades |>
  group_by(Group) |>
  summarise(nb_missed_exam = sum(is.na(Exam))) |>
  ggplot(aes(x=Group, y=nb_missed_exam)) +geom_col() + labs(title="Nb of students who missed the exam in each group", y="Nb of students who missed the exam")
```

## Question 10

```{r}
longgrades <- grades |>
  pivot_longer(cols=-c(Id, Group))
```

## Question 11
```{r}
longgrades |> summarise(totalnb_missing=sum(is.na(value)))
```
## Question 12
```{r}
missinggrade <- longgrades |> group_by(Id) |>
  summarise(missing_gradestd=sum(is.na(value)))
```

```{r}
ggplot(missinggrade, aes(x=missing_gradestd)) + geom_histogram(binwidth = 1, alpha=0.9) +
  labs(title="Missing grades per student",x="Nb of missing grades",y="Frequency")
```

## Question 13
```{r}
longgrades |> 
  filter(name=='Exam') |>
  group_by(Group) |>
  summarise(nb_missed_exam = sum(is.na(value)))
```
#Question 14
```{r}
library(stringr)
```

```{r}
q14 <- longgrades |> 
  filter(str_starts(name,"Online")) |>
  group_by(Id) |>
  summarise(nb_missed_exam_online = sum(is.na(value)))

```

# Question 15
```{r}
merged_q14 <- grades |> 
  left_join(q14, by="Id")
```

```{r}
merged_q14 |>
  group_by(nb_missed_exam_online) |>
  ggplot(aes(x=Exam)) + geom_bar() +xlab("Grades at the exam")+ ylab("Number of test missed online")
```

# Question 16
```{r}
q16 <- grades |>
  select(Id, starts_with("MCQ_")) 
missed_counts <- rowSums(is.na(q16))
q16 <- mutate(q16, Missed = missed_counts > 0) |>
  select(-starts_with("MCQ_"))
q16
knitr::kable(q16)
```
# Question 17

```{r}
q17 <- q16 %>%
  left_join(grades %>% select(Id, Group), by = "Id") %>%
  group_by(Group) %>%
 mutate(count=sum(Missed), 
           P_missed = (count / n()) * 100) |>
  select(-c(Id, Missed, count))
knitr::kable(q17)
```

# Question 18
```{r}
avgexam <- grades |>
  select(Group, Exam)|>
  group_by(Group) |>
  mutate(avg=mean(Exam, na.rm=TRUE)) |>
  distinct(Group, .keep_all=TRUE) |>
  select(c(-Exam))
```



```{r}
q18 <- inner_join(q17,avgexam, by="Group") 
ggplot(q18, aes(x = P_missed, y = avg), size=6) +
  geom_point(aes(color = Group))
```

